server:
    port: 8001
spring:
    application:
        name: eureka
    security:
        user:
            name: wy13656
            password: wy13656
eureka:
    client:
        allow-redirects: false
        fetch-registry: false
        server-url:
            defaultZone: http://localhost:8005/eureka
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 2000